Repository Roman-wdesign/Weather-app, pull requests merged in 2024-12, with the labels that each got.

#36 feat/dev get pressure + humidity
  src/features/WeatherHourly/main-component/ui/HourlyComponent.vue
  src/features/WeatherNow/item-weather/model/types.ts
  src/features/WeatherNow/item-weather/ui/TheItemWeather.vue
Labels: good first issue

#37 fix: editing tests
  src/features/WeatherHourly/main-component/ui/HourlyComponent.spec.ts
  src/features/WeatherNow/item-weather/ui/TheItemWeather.spec.ts
Labels: bug

#44 chore: add linting, boundaries fsd settings
  .eslintrc.cjs
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/features/WeatherHourly/main-component/ui/HourlyComponent.vue
  tsconfig.json
Labels: documentation, file config

#46 feat: add air pollution api
  src/features/WeatherNow/item-weather/model/types.ts
  src/features/WeatherNow/item-weather/ui/TheItemWeather.spec.ts
  src/features/WeatherNow/item-weather/ui/TheItemWeather.vue
  src/features/WeatherNow/main-component/api/generateNowWeather.spec.ts
  src/features/WeatherNow/main-component/api/generateNowWeather.ts
  src/features/WeatherNow/main-component/model/useWeatherNow.ts
  src/features/WeatherNow/main-component/ui/WeatherNow.vue
  src/shared/composables/localStorage/saved-cities/model/useSavedCities.spec.ts
  src/shared/composables/localStorage/saved-cities/model/useSavedCities.ts
Labels: good first issue

#47 Refactor/logic
  src/features/WeatherHourly/main-component/api/generateHourlyWeather.ts
  src/features/WeatherHourly/main-component/ui/HourlyComponent.vue
  src/features/WeatherNow/item-weather/ui/TheItemWeather.spec.ts
  src/features/WeatherNow/item-weather/ui/TheItemWeather.vue
  src/features/WeatherNow/main-component/api/generateNowWeather.spec.ts
  src/features/WeatherNow/main-component/api/generateNowWeather.ts
  src/features/WeatherNow/main-component/lib/useDragAndDrop.ts
  src/features/WeatherNow/main-component/model/useWeatherNow.ts
  src/features/WeatherNow/main-component/ui/WeatherNow.vue
  src/shared/assets/image/svg/condtitions/day/index.ts
  src/shared/assets/image/svg/condtitions/day/ui/IconBrokenCloudsDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconClearSkyDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconFewCloudsDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconMistDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconRainDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconScatteredCloudsDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconShowerRainDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconSnowDay.vue
  src/shared/assets/image/svg/condtitions/day/ui/IconThunderstormDay.vue
  src/shared/assets/image/svg/condtitions/night/index.ts
  src/shared/assets/image/svg/condtitions/night/ui/IconBrokenCloudsNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconClearSkyNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconFewCloudsNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconMistNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconRainNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconScatteredCloudsNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconShowerRainNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconSnowNight.vue
  src/shared/assets/image/svg/condtitions/night/ui/IconThunderstormNight.vue
  src/shared/assets/image/svg/humidity-and-pressure/index.ts
  src/shared/assets/image/svg/humidity-and-pressure/ui/IconHumidity.vue
  src/shared/assets/image/svg/humidity-and-pressure/ui/IconPressure.vue
  src/shared/assets/image/svg/wind-directions/index.ts
  src/shared/assets/image/svg/wind-directions/ui/IconEast.vue
  src/shared/assets/image/svg/wind-directions/ui/IconNorth.vue
  src/shared/assets/image/svg/wind-directions/ui/IconNorthEast.vue
  src/shared/assets/image/svg/wind-directions/ui/IconNorthWest.vue
  src/shared/assets/image/svg/wind-directions/ui/IconSouth.vue
  src/shared/assets/image/svg/wind-directions/ui/IconSouthEast.vue
  src/shared/assets/image/svg/wind-directions/ui/IconSouthWest.vue
  src/shared/assets/image/svg/wind-directions/ui/IconWest.vue
  src/shared/composables/fetch/api/useFetch.ts
  src/shared/composables/localStorage/saved-cities/model/useSavedCities.spec.ts
  src/shared/composables/localStorage/saved-cities/model/useSavedCities.ts
  src/shared/composables/localStorage/storage/model/useLocalStorage.ts
  src/shared/ui/pagination/ui/PaginationComponent.vue
Labels: wontfix

#49 fix: to https reverseGeo
  src/features/WeatherHourly/main-component/ui/HourlyComponent.vue
  src/features/WeatherNow/item-weather/ui/TheItemWeather.vue
  src/features/WeatherNow/main-component/model/useWeatherNow.ts
  src/features/WeatherNow/main-component/ui/WeatherNow.vue
  src/shared/config/index.ts
  src/widgets/navbar/ui/TheNavbar.vue
  tailwind.config.js
Labels: bug
